fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        stages: [commit]
        args: ["--style=file", "-i"]
      - id: clang-tidy
        stages: [commit]
        args: [--, -Iinclude/, -Ibindings/c/include, -Iextern/catch2/include, -Ibindings/python/extern/pybind11/include]
      - id: cppcheck
        stages: [commit]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    - id: codespell
      exclude: COMMIT_EDITMSG
      stages: [commit]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
    - id: detect-secrets
      stages: [commit]