fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        stages: [commit]
        args: ["--style=file", "-i"]
      - id: clang-tidy
        stages: [commit]
        args: [--, -Iinclude/, -Ibindings/c/include, -Iextern/catch2/include]
      - id: cppcheck
        stages: [commit]
        args: ["-q", "--suppress=*:extern/*", "--std=c++14", "-Iextern/catch2/include/", "-Ibindings/c/include/", "-Iinclude/", "--enable=all", "--suppress=unmatchedSuppression", "--suppress=missingIncludeSystem", "--suppress=unusedFunction", "--suppress=toomanyconfigs", "--max-ctu-depth=3", "--error-exitcode=1"]