name: base lib tests


on:
  pull_request:
    branches: ["master", "release", "test-me*", "base-lib"]
  push:
    branches: ["master", "release", "test-me*"]


jobs:
  base_lib_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build base lib
        run: |
          mkdir build && cd build
          cmake .. -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=ON
          cmake --build .
      - name: Run tests
        working-directory: build
        run: ctest