name: base lib tests


on:
  pull_request:
    branches: ["master", "release", "test-me*", "base-lib"]
  push:
    branches: ["master", "release", "test-me*"]


jobs:
  base_lib_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Installing gcovr
        run: |
          python -m pip install -U pip
          python -m pip install -U gcovr
      - name: Configure build
        working-directory: ${{runner.workspace}}
        run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=ON -DCODE_COVERAGE=ON $GITHUB_WORKSPACE
      - name: Build lib + tests
        working-directory: ${{runner.workspace}}/build
        run: cmake --build .
      - name: Run tests with coverage
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . -t calculator_test_coverage
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          files: ${{runner.workspace}}/build/RAFFY_TEST_COVERAGE.xml
          fail_ci_if_error: true
          verbose: true
          dry_run: true