name: calculator python bindings test

on:
  pull_request:
    branches: ["master", "release", "test-me*", "python-bindings"]
  push:
    branches: ["master", "release", "test-me*"]


jobs:
  python_tests:
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python}}
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pytest
      - name: Build python bindings
        working-directory: bindings/python
        run: python -m pip install .[test]
      - name: Run tests
        working-directory: bindings/python
        run: pytest tests


